server:
  port: 8080
spring:
  application:
    name: game-attendance-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/game_attendance
    driver-class-name: org.postgresql.Driver
    username: ${USER}
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
